name: quiz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/harrypotter.jpg
    - lib/assets/harry.jpg
    - lib/assets/animais.jpg
    - lib/assets/banco.jpg
    - lib/assets/casas.jpg
    - lib/assets/cofre.jpg
    - lib/assets/coruja.jpg
    - lib/assets/diretor.jpg
    - lib/assets/dobby.jpg
    - lib/assets/feitico.jpg
    - lib/assets/harry-quadri.jpg
    - lib/assets/Horcruxes.jpg
    - lib/assets/levitar.jpg
    - lib/assets/mae.jpg
    - lib/assets/morto.jpg
    - lib/assets/padrinho.jpg
    - lib/assets/plataforma.jpg
    - lib/assets/patrono.jpg
    - lib/assets/quadribol.jpg
    - lib/assets/trouxas.jpg
    - lib/assets/varinha.jpg

